name: Test OSHy-X
on: [push]

jobs:
  test-oshyx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt
          pip install -e
      -name: Run pytest
        run: python -m pytest test/